### PR TITLE
Fix Visual Studio 2013 build

### PR DESCRIPTION
**Pull request by samuelig**
There are issues with inline attribute (not supported on MSVC 2013) and offsetof() (undefined on MSVC 2013). This patch series fixes both.

Checked compilation on MSVC 2013 and GCC (GNU/Linux).

### CODE REVIEW

**Comment by samuelig** [comment]
For the inline one, we can use this instead:

```C
/*
 * C99 inline keyword
 */
#ifndef inline
#  ifdef __cplusplus
     /* C++ supports inline keyword */
#  elif defined(__GNUC__)
#    define inline __inline__
#  elif defined(_MSC_VER)
#    define inline __inline
#  elif defined(__ICL)
#    define inline __inline
#  elif defined(__INTEL_COMPILER)
     /* Intel compiler supports inline keyword */
#  elif defined(__WATCOMC__) && (__WATCOMC__ >= 1100)
#    define inline __inline
#  elif (__STDC_VERSION__ >= 199901L)
     /* C99 supports inline keyword */
#  else
#    define inline
#  endif
#endif

```

Let me know what you prefer.

**Comment by bpeel** [comment]
Yes, I think it would be better to continue using the C99 standard `inline` keyword on non-MSVC compilers. I don’t think it’s worth adding the ifdef’s for all of those compilers because VkRunner already heavily uses other C99 features so it would probably already have other problems. My preferred approach would be to add a VR_INLINE macro in vr-util.h that looks like this:

```C
#ifdef _MSVC_VER
#define VR_INLINE __inline
#else 
#define VR_INLINE inline
#endif 
```

Using VR_INLINE will force us to remember to include vr-util.h whenever we add another inline function.

For the second patch, it seems a bit hacky to add it to vr-util.h because nothing in vr-util uses offsetof. I think it would be better to add it to all of vr-feature-offsets.c, vr-list.h, vr-pipeline.c, vr-pipeline-key.c and vr-vk.c.

**Comment by samuelig** [comment]
OK, thanks for the feedback.

**Comment by samuelig** [comment]
Please ignore this.

**Comment by samuelig** [comment]
Now it is fine (fixed ```#ifdef _MSC_VER```).

**Comment by bpeel** [comment]
Looks good to me, thanks!

Reviewed-by: Neil Roberts <nroberts@igalia.com>

**Pull request closed without merging**
