### PR TITLE
Add buffer memory barriers for SSBOs at start and end of command buffer

### PR DESCRIPTION
**Pull request by bpeel**
As mentioned in issue #52, we need to have barriers in order to transition from accessing SSBOs from the host and in the shaders.

The first two patches change the semantics of updating SSBOs and UBOs so that they also cause the command buffer to be flushed. This is discussed in issue #46.

### CODE REVIEW

**Comment by paulthomson** [comment]
Thanks for doing this! I *believe* that you do not need the barriers for host -> device. You just need to call `vkFlushMappedMemoryRanges` (if the memory is not host coherent), then call `vkQueueSubmit` on the command buffer (in that order). All host writes flushed before the submit can be read by the device by commands in the submitted command buffer. This is due to `6.9. Host Write Ordering Guarantees` in the Vulkan spec. 

The device -> host barriers look good to me. 

I will try to get another person to verify.

**Comment by bpeel** [comment]
Thanks for taking a look. If that is the case then I guess we only need the last patch and the branch doesn’t need to be dependent on making buffer updates a flush point. On the other hand it might be a good idea to do anyway to match what Amber seems to have chosen to do.

**Comment by paulthomson** [comment]
I got confirmation that what I said is correct (although the code was not reviewed).

**Comment by bpeel** [comment]
Thanks. I’ve force pushed the branch to contain just the last patch. I’ve moved the rest of the patches to a [separate branch](https://github.com/Igalia/vkrunner/tree/nroberts/buffer-update-flush) as it’s now unrelated.

**Comment by paulthomson** [comment]
Looks good to me!

**Pull request merged**
